blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/fortinpy85/jddb/blob/main/README.md
    about: Check the documentation for setup instructions and guides
  - name: 💬 Discussions
    url: https://github.com/fortinpy85/jddb/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 🔒 Security Issue
    url: https://github.com/fortinpy85/jddb/security/advisories/new
    about: Report security vulnerabilities privately