"""Add cascade delete to job_descriptions foreign keys

Revision ID: 0dcd41b28d93
Revises: 8dfdfb2859ca
Create Date: 2025-10-13 20:26:08.889347

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "0dcd41b28d93"
down_revision = "8dfdfb2859ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("content_chunks_section_id_fkey"), "content_chunks", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("content_chunks_job_id_fkey"), "content_chunks", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "content_chunks",
        "job_descriptions",
        ["job_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "content_chunks",
        "job_sections",
        ["section_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("data_quality_metrics_job_id_fkey"),
        "data_quality_metrics",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "data_quality_metrics",
        "job_descriptions",
        ["job_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("job_metadata_job_id_fkey"), "job_metadata", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "job_metadata", "job_descriptions", ["job_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("job_sections_job_id_fkey"), "job_sections", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "job_sections", "job_descriptions", ["job_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("job_skills_job_id_fkey"), "job_skills", type_="foreignkey")
    op.create_foreign_key(
        None, "job_skills", "job_descriptions", ["job_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "job_skills", type_="foreignkey")
    op.create_foreign_key(
        op.f("job_skills_job_id_fkey"),
        "job_skills",
        "job_descriptions",
        ["job_id"],
        ["id"],
    )
    op.drop_constraint(None, "job_sections", type_="foreignkey")
    op.create_foreign_key(
        op.f("job_sections_job_id_fkey"),
        "job_sections",
        "job_descriptions",
        ["job_id"],
        ["id"],
    )
    op.drop_constraint(None, "job_metadata", type_="foreignkey")
    op.create_foreign_key(
        op.f("job_metadata_job_id_fkey"),
        "job_metadata",
        "job_descriptions",
        ["job_id"],
        ["id"],
    )
    op.drop_constraint(None, "data_quality_metrics", type_="foreignkey")
    op.create_foreign_key(
        op.f("data_quality_metrics_job_id_fkey"),
        "data_quality_metrics",
        "job_descriptions",
        ["job_id"],
        ["id"],
    )
    op.drop_constraint(None, "content_chunks", type_="foreignkey")
    op.drop_constraint(None, "content_chunks", type_="foreignkey")
    op.create_foreign_key(
        op.f("content_chunks_job_id_fkey"),
        "content_chunks",
        "job_descriptions",
        ["job_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("content_chunks_section_id_fkey"),
        "content_chunks",
        "job_sections",
        ["section_id"],
        ["id"],
    )
    # ### end Alembic commands ###
