"""Add translation memory tables

Revision ID: 0e13c9b0cf72
Revises: 60d097be6a73
Create Date: 2025-10-17 10:40:44.593134

"""

# revision identifiers, used by Alembic.
revision = "0e13c9b0cf72"  # pragma: allowlist secret
down_revision = "60d097be6a73"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
