"""Add CASCADE delete to job_comparisons foreign keys

Revision ID: 60d097be6a73
Revises: 0dcd41b28d93
Create Date: 2025-10-14 06:44:59.336083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d097be6a73'
down_revision = '0dcd41b28d93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('job_comparisons_job1_id_fkey'), 'job_comparisons', type_='foreignkey')
    op.drop_constraint(op.f('job_comparisons_job2_id_fkey'), 'job_comparisons', type_='foreignkey')
    op.create_foreign_key(None, 'job_comparisons', 'job_descriptions', ['job2_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_comparisons', 'job_descriptions', ['job1_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_comparisons', type_='foreignkey')
    op.drop_constraint(None, 'job_comparisons', type_='foreignkey')
    op.create_foreign_key(op.f('job_comparisons_job2_id_fkey'), 'job_comparisons', 'job_descriptions', ['job2_id'], ['id'])
    op.create_foreign_key(op.f('job_comparisons_job1_id_fkey'), 'job_comparisons', 'job_descriptions', ['job1_id'], ['id'])
    # ### end Alembic commands ###
