"""Create initial job description tables

Revision ID: fba902742fb7
Revises:
Create Date: 2025-09-12 10:39:21.560897

"""

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision = "fba902742fb7"
down_revision = "f77d403fc114"  # Now depends on pgvector extension migration
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_descriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_number", sa.String(length=20), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("classification", sa.String(length=10), nullable=True),
        sa.Column("language", sa.String(length=2), nullable=True),
        sa.Column("file_path", sa.String(length=1000), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column(
            "processed_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_number"),
    )
    op.create_table(
        "job_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("section_type", sa.String(length=50), nullable=True),
        sa.Column("section_content", sa.Text(), nullable=True),
        sa.Column("section_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_descriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("reports_to", sa.String(length=500), nullable=True),
        sa.Column("department", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("fte_count", sa.Integer(), nullable=True),
        sa.Column("salary_budget", sa.DECIMAL(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_descriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("chunk_text", sa.Text(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=True),
        sa.Column("embedding", VECTOR(1536), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_descriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["job_sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("content_chunks")
    op.drop_table("job_metadata")
    op.drop_table("job_sections")
    op.drop_table("job_descriptions")
    # ### end Alembic commands ###
